### ISSUE TITLE
Accept environment option with ng-afelio start

### ISSUE THREAD

**Issue by mowgliLab** [gilsdav/ng-afelio#10]
With the command ng start, we usually pass the `-c=node` option to use node build and environment.

This allow to have local behaviors with mock and labels. But it also allow to disable build optimization for faster build and easier debug (no uglifying/minifying).

Could you add this feature to ng-afelio start ?

Most important is for main project. I don't think that UIKit need this feature.

Alain

**Comment by gilsdav** [comment]
Hello, 
I will do it but you can actually use this workaround on your package.json :
`"start": "ng serve -c=node; ng-afelio uiServe"`

**Comment by gilsdav** [comment]
--env available like on "build" on version 0.0.1-4
