### ISSUE TITLE
Moving assets with ng-afelio style

### ISSUE THREAD

**Issue by mowgliLab** [gilsdav/ng-afelio#11]
When running `ng-afelio style` the style is well imported into main project.

But it is still needed to copy/paste assets in `src` folder and rename path for fonts and so one.

Is there a way to copy assets in src folder and adapt path for assets in scss files ?

Alain

**Comment by gilsdav** [comment]
One fix is implemented in 0.0.1-4 version. Use "Absolute path" because webpack check every Relative path as "Entry file" and will copy them into the root of dist folder.
So replace `url('assets/images/test.jpg')` to `url('/assets/images/test.jpg')` will fix sass error and will avoid duplicate.
