### ISSUE TITLE
ouverture automatique de l'application

### ISSUE THREAD

**Issue by AHEAfelio** [gilsdav/ng-afelio#27]
ajouter le flag  '-o' afin d'ouvrir automatiquement un onglet navigateur lors du npm start

**Comment by gilsdav** [comment]
@AHEAfelio Je penses que c'est mieux de mettre une option générique pour la configuration du cli d'angular. Il sera donc possible d'ajouter le open comme ça:

`ng-afelio start --ng="--open --port=4300"`

Qu'en penses-tu ?

**Comment by gilsdav** [comment]
Available since version `0.1.0`
