### ISSUE TITLE
Swagger codegen

### ISSUE THREAD

**Issue by TKAafelio** [gilsdav/ng-afelio#3]
Generate model and service in the web application from a swagger with possibilities to customize it.

**Comment by gilsdav** [comment]
En attente de correction d'un bug dans la librairie utilisée avant de merger.
https://github.com/cyclosproject/ng-swagger-gen/issues/84

**Comment by gilsdav** [comment]
Normally fixed on version 1.2.1 of ng-swagger-gen.

**Comment by gilsdav** [comment]
Available since 0.0.1-2
