### ISSUE TITLE
import style shortcut

### ISSUE THREAD

**Issue by AHEAfelio** [gilsdav/ng-afelio#32]
ajouter l'option :
---
"stylePreprocessorOptions": {
                            "includePaths": [
                                "styles"
                            ]
                        },
---

dans " angular.json -> projects-> #nomDuProjet -> architect-> options "

cela permet de pouvoir importer le fichier de variables SCSS dans n'importe quel composant de l'application sans devoir écrire un chemin qui souvent, peut s'avérer être très long…

**Comment by gilsdav** [comment]
Available since version `0.1.0`
