### ISSUE TITLE
Migrer les templates vers des schematics Angular

### ISSUE THREAD

**Issue by gilsdav** [gilsdav/ng-afelio#49]
https://developer.okta.com/blog/2019/02/13/angular-schematics#:~:text=Add%20Support%20for%20ng%20add%20with%20Angular%20CLI&text=Create%20src%2Fng%2Dadd%2F,invoke%20the%20my%2Dcomponent%20schematic.&text=Run%20npm%20run%20build%20in,my%2Dtest%2Dapp%20project.

https://dev.to/thisdotmedia/schematics-building-blocks-2mg3

ng config cli.defaultCollection ng-afelio

https://github.com/ionic-team/angular-toolkit

- [x] mocks
- [x] module
- [x] UI-Kits
- [x] ng-add
- [x] new

**Comment by gilsdav** [comment]
- [ ] mocks
- [ ] module
- [ ] open-api
- [ ] UI-Kits

**Comment by gilsdav** [comment]
Ng-add partiellement implémenté. Ajouter la génération de l'ui-kit dans ng-add, une fois celle-ci migrée.

**Comment by gilsdav** [comment]
UI-kit ajouté dans ng-add et disponible également après via "ng-afelio i uikit"

**Comment by gilsdav** [comment]
new doit faire cette liste d'actions:

1. `ng-new` angular
2. `ng-add` ng-afelio

**Comment by DBG-Afelio** [comment]
Créer le ng-afelio.json au projet au moment du ng-add
