### ISSUE TITLE
Ajouter la possibilité de merger plusieurs swaggers

### ISSUE THREAD

**Issue by gilsdav** [gilsdav/ng-afelio#66]
https://www.npmjs.com/package/swagger-merger

**Comment by gilsdav** [comment]
Via Swagger-hub, cela est déjà possible via : https://api.swaggerhub.com/apis/{owner}/{api}/{version}?resolved=true

**Comment by DBG-Afelio** [comment]
A investiguer... Sur NAG on constate que les refs externes (directement utilisés dans une API) sont liés mais pas générés

**Comment by gilsdav** [comment]
swagger-merger ne semble pas aider. La seule façon trouvée est de merger les swagger en utilisant le cli de codegen avant la génération back et front.
