### ISSUE TITLE
Front pouvant prendre un/des json en entrés (jsonServer) pour gérer les traductions via une interface web.

### ISSUE THREAD

**Issue by gilsdav** [gilsdav/ng-afelio#75]

**Comment by remylavergne** [comment]
J'ai une idée très précise de la chose, il faudra en parler pour voir si c'est viable, et si ça existe pas déjà :D

**Comment by DBG-Afelio** [comment]
- [x] Intégrer la version Ethias de l'application de traduction.
 - [x] Présenter le(s) fichiers de traductions en arborescence.
 - [x] Intégrer un fichier de description permettant de mettre des commentaires dans l'application.
 - [x] Download JSON ZIPpé du résultat.
 - [x] Sauvegarde JSON (pas sûr) :)

En fait, ce serait un projet indépendant et exposable au client qui pourrait uploadé des fichiers json et profiter de l'interface. A la validation, il récupère les fichiers json mis à jour.

On le laisse ici pour garder une trace!!!
MAXIME GINETTI

**Comment by Ginetti** [comment]
@DBG-Afelio je te laisse voir pour le serveur public ou déployer l'app

**Comment by gilsdav** [comment]
http://translate.doc.afeliodev.local/
